# SPDX-License-Identifier: PMPL-1.0-or-later
name: ClusterFuzzLite PR
on:
  pull_request:
    paths:
      - '**/*.rs'
permissions: read-all
jobs:
  PR:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [address, undefined]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: google/clusterfuzzlite/actions/build_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          sanitizer: ${{ matrix.sanitizer }}
          language: rust
      - uses: google/clusterfuzzlite/actions/run_fuzzers@884713a6c30a92e5e8544c39945cd7cb630abcd1 # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fuzz-seconds: 300
          sanitizer: ${{ matrix.sanitizer }}
          mode: code-change
          output-sarif: true
      - uses: github/codeql-action/upload-sarif@662472033e021d55d94146f66f6058822b0b39fd # v3
        if: always()
        with:
          sarif_file: vulnerabilities.sarif
